/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  SpookyButton as SpookyButton
} from './components/spooky-button/spooky-button';

declare global {
  interface HTMLSpookyButtonElement extends SpookyButton, HTMLElement {
  }
  var HTMLSpookyButtonElement: {
    prototype: HTMLSpookyButtonElement;
    new (): HTMLSpookyButtonElement;
  };
  interface HTMLElementTagNameMap {
    "spooky-button": HTMLSpookyButtonElement;
  }
  interface ElementTagNameMap {
    "spooky-button": HTMLSpookyButtonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "spooky-button": JSXElements.SpookyButtonAttributes;
    }
  }
  namespace JSXElements {
    export interface SpookyButtonAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  SpookySkeletons as SpookySkeletons
} from './components/spooky-skeletons/spooky-skeletons';

declare global {
  interface HTMLSpookySkeletonsElement extends SpookySkeletons, HTMLElement {
  }
  var HTMLSpookySkeletonsElement: {
    prototype: HTMLSpookySkeletonsElement;
    new (): HTMLSpookySkeletonsElement;
  };
  interface HTMLElementTagNameMap {
    "spooky-skeletons": HTMLSpookySkeletonsElement;
  }
  interface ElementTagNameMap {
    "spooky-skeletons": HTMLSpookySkeletonsElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "spooky-skeletons": JSXElements.SpookySkeletonsAttributes;
    }
  }
  namespace JSXElements {
    export interface SpookySkeletonsAttributes extends HTMLAttributes {
      
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
